### `ENVIRONMENT SETUP`

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 1000)

import warnings
warnings.filterwarnings("ignore")

### `SETTING WORKING DIR`

In [2]:
import os

# Dir location with csv files
path = 'G:\\ML - Datahack\\HDFC Bank'

os.chdir(path)

%pwd

'G:\\ML - Datahack\\HDFC Bank'

### `IMPORTING DATA`

In [3]:
# Train Data
train = pd.read_csv('Train.csv', low_memory=False)

# Drop ID column
train.drop('Col1', axis=1, inplace = True)

# Drop duplicate values if any
train = train.drop_duplicates()

# Test Data
test = pd.read_csv('Test.csv', low_memory=False)

In [4]:
train.head()

Col2          Col3          Col4          Col5          Col6          Col7  \
0     1  1.086711e+04  8.648345e+03  1.576618e+04  2.890466e+04  5.273655e+03   
1     0  2.584312e+05  2.179633e+05  1.866287e+05  1.866287e+05  2.154519e+05   
2     0  1.459355e+07  1.260060e+07  1.100315e+07  1.010315e+07  1.879882e+07   
3     0  6.727043e+05  8.181116e+05  6.794893e+05  6.794893e+05  8.257254e+05   
4     0 -1.218742e+06 -3.005361e+06 -1.666241e+05 -2.403574e+06  2.583183e+06   

           Col8          Col9         Col10         Col11         Col12  \
0  2.346153e+04  1.285597e+04  2.871509e+04  9.114586e+03  3.043078e+04   
1  1.923615e+05  1.726538e+05  1.666974e+05  2.013518e+05  1.859404e+05   
2  1.514035e+07  5.320778e+06  6.906324e+06  9.368338e+06  1.113330e+07   
3  7.605803e+05  3.577134e+05  4.236612e+05  4.304848e+05  4.065539e+05   
4  2.086546e+06  5.938358e+06  5.446532e+06  3.473444e+06  3.262168e+06   

       Col13      Col14      Col15      Col16     Col17     Col18  Col19  \
0   9.293496   8.570479  10.063117  10.271758  0.548538  0.403366    NaN   
1  12.462385  12.280493  12.167132  12.136876  1.167898  2.676398    NaN   
2  16.496090  16.749305  16.532874  16.128357  1.145182  2.203874    NaN   
3  13.419061  13.624018  13.541837  13.429097  1.204010  0.536304    NaN   
4        NaN  14.764533  14.551021        NaN       NaN       NaN    NaN   

   Col20     Col21     Col22     Col23     Col24     Col25     Col26  \
0    NaN  1.486524  1.728324  0.993441  1.297050  0.137398  0.115987   
1    NaN  0.792123  0.934556  0.893203  0.966620  0.753892  0.808295   
2    NaN  0.422264  0.498347  0.683582  0.735339  0.808115  0.776910   
3    NaN  0.437243  0.521341  0.623499  0.534531 -0.125829  0.388830   
4    NaN       NaN  1.344637       NaN  1.563430 -0.113101  0.617486   

      Col27     Col28  Col29  Col30  Col31  Col32  Col33  Col34  Col35  Col36  \
0  0.260428  1.414214      1      1      1      1      1      1      0      6   
1  1.414214       NaN      1      1      3      4      4      0      4      5   
2  1.414214       NaN      3      3      4     12      4      0      2      4   
3 -1.414214       NaN      2      2      2     24      1      0      1      4   
4  1.414214       NaN      4      3      4     68      8      0      2      4   

   Col37  Col38  Col39  Col40  Col41   Col42   Col43  Col44  Col45  Col46  \
0    NaN    NaN    NaN    NaN    NaN    6.07    6.07      2      3      2   
1    NaN    NaN    NaN    NaN    NaN  116.65  116.65      3      0      2   
2    NaN    1.0    NaN    NaN    2.0   33.28   33.28      2      1      2   
3    NaN    NaN    NaN    NaN    2.0   -7.75   -7.75      2      1      2   
4    NaN    3.0    NaN    NaN    2.0     NaN     NaN      1      2      1   

   Col47  Col48  Col49  Col50  Col51  Col52  Col53  Col54  Col55  Col56  \
0      3      2      2      2      2      1      3      1      3      1   
1      0      2      0      1      0      3      0      2      0      2   
2      0      1      0      1      0      2      1      2      0      1   
3      1      1      1      1      1      2      1      2      1      1   
4      2      1      2      1      2      1      2      1      2      1   

   Col57  Col58  Col59  Col60  Col61  Col62  Col63  Col64  Col65  Col66  \
0      2      1      2      1      1      1      1      1      1      1   
1      0      1      0      2      0      2      0      2      0      1   
2      0      1      0      1      1      1      0      1      0      1   
3      1      1      1      2      0      2      0      1      0      1   
4      2      1      2      0      2      0      2      0      2      0   

   Col67  Col68  Col69  Col70  Col71  Col72  Col73  Col74  Col75  Col76  \
0      1      3      1      3      1      3      1      3      1      2   
1      0      2      0      2      0      2      0      2      0      2   
2      0      2      1      2      1      1      0      1      0      2   
3      0      2      1 

In [5]:
test.head()

Col1          Col3          Col4          Col5          Col6  \
0  RIGD58ZWD  8.167140e+04  8.614542e+04  7.532296e+04  7.532296e+04   
1  RIH660YDS -1.362824e+07 -4.493043e+06 -3.777257e+06 -4.493043e+06   
2  RIH660Q96  1.302700e+06  1.341449e+06  1.240085e+06  1.341449e+06   
3  RIYDO15W1  1.932258e+05  1.454433e+05  1.929148e+05  1.454433e+05   
4  RIYBGC1ZD  3.913385e+05  1.987337e+05  1.703432e+05  1.987337e+05   

           Col7          Col8          Col9         Col10         Col11  \
0  1.125174e+05  1.002778e+05  2.038915e+04  3.053853e+04  8.395911e+04   
1 -4.749764e+06 -4.749764e+06  1.147556e+07  1.147556e+07  1.272055e+07   
2  1.477503e+06  1.477503e+06  3.904086e+05  3.904086e+05  4.979106e+05   
3  1.318250e+04  1.318250e+04  8.650108e+04  8.650108e+04  5.896693e+03   
4  3.046536e+05  3.046536e+05  2.528307e+05  2.528307e+05  3.034449e+05   

          Col12      Col13      Col14      Col15      Col16     Col17  \
0  8.138800e+04  11.310459  11.630863  11.515700  11.229540  1.143681   
1  1.272055e+07        NaN        NaN        NaN        NaN       NaN   
2  4.979106e+05  14.079949  14.205864  14.205864  14.109261  1.081739   
3  5.896693e+03  12.171615   9.486645   9.486645  11.887541  0.753925   
4  3.034449e+05  12.877328  12.626931  12.626931  12.199721  1.166667   

       Col18       Col19      Col20     Col21     Col22     Col23     Col24  \
0   0.879545         NaN        NaN  0.236683  0.746188  0.405435  0.811625   
1  -2.935756 -232.140528 -94.995287       NaN       NaN       NaN       NaN   
2   0.943850    2.122872   0.857057  0.291035  0.336995  0.291035  0.336995   
3   1.978542         NaN        NaN  0.594741  0.447312  0.594741  0.447312   
4  63.849949         NaN        NaN  1.272208  0.996032  1.272208  0.996032   

      Col25     Col26     Col27  Col28  Col29  Col30  Col31  Col32  Col33  \
0  0.086109  0.238817  0.150242    NaN      3      3      6      6      6   
1 -0.483522 -0.308259 -0.742190    NaN      6      5      7     19      9   
2 -0.108229 -0.095389 -0.053413    NaN      2      2      2      3      1   
3  0.441902  0.383241  0.681768    NaN      4      4      5      5      5   
4  0.507021  0.539030  0.742665    NaN      1      1      1      1      1   

   Col34  Col35  Col36  Col37  Col38  Col39  Col40  Col41       Col42  \
0      0      1      5   19.0    NaN    NaN   39.0    NaN    1.665000   
1      0      2      6    2.0    0.0    NaN    5.0    4.0 -126.895000   
2      0      1      6    NaN    NaN    NaN    NaN    5.0   -0.613333   
3      0      1      6    6.0    5.0    NaN    1.0    NaN   28.863333   
4      0      1      6    NaN    NaN    NaN    NaN    NaN  363.116667   

        Col43  Col44  Col45  Col46  Col47  Col48  Col49  Col50  Col51  Col52  \
0    1.665000      2      2      2      2      2      1      0      0      2   
1 -126.895000      3      2      3      2      2      2      2      2      3   
2   -0.613333      1      4      1      4      1      2      1      0      1   
3   28.863333      3      2      3      2      3      1      2      0      3   
4  363.116667      5      0      4      0      3      0      3      0      5   

   Col53  Col54  Col55  Col56  Col57  Col58  Col59  Col60  Col61  Col62  \
0      2      2      2      2      1      0      0      2      0      2   
1      2      3      2      2      2      2      2      1      1      1   
2      4      1      4      1      2      1      0      1      1      1   
3      2      3      2      3      1      2      0      1      1      1   
4      0      4      0      3      0      3      0      2      0      1   

   Col63  Col64  Col65  Col66  Col67  Col68  Col69  Col70  Col71  Col72  \
0      0      2      0      0      0      2      2      2      2      1   
1      1      0      1      0      1      3      2      3      2      3   
2      1      1      1      1      0      1      4      1      4      1   
3      1      1      0      0      0      1      0      1      0      1   
4

### `CHECKING DATASET SHAPE`

In [6]:
train.shape

(16416, 2394)

In [7]:
test.shape

(20442, 2394)

### `CHECKING CLASS BALANCE`

In [8]:
# Count 
train.Col2.value_counts()

0    14776
1     1640
Name: Col2, dtype: int64

In [9]:
# Percentage
round(train.Col2.value_counts()/len(train)*100,2)

0    90.01
1     9.99
Name: Col2, dtype: float64

### `CHECK FOR DUPLICATE COLUMNS`

In [10]:
cols = train.T.drop_duplicates().T.columns.values
train = train[cols]

In [11]:
train.shape

(16416, 2265)

In [12]:
col1  = train.drop('Col2', axis=1).columns.values
col2  = test.drop('Col1', axis=1).columns.values

In [13]:
cols_miss = []

for x in col2:
    if x not in col1:
        cols_miss.append(x)
        
print(f'{len(cols_miss)}Features missing in Test Set...')

129Features missing in Test Set...


In [14]:
# train.drop(columns=cols3, axis=1, inplace=True)
test.drop(columns=cols_miss, axis=1, inplace=True)

In [15]:
test.shape

(20442, 2265)

### `CHECK FOR MISS-MATCH IN DATA TYPES`

In [16]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16416 entries, 0 to 17520
Columns: 2265 entries, Col2 to Col2397
dtypes: float64(816), int64(1447), object(2)
memory usage: 284.4+ MB


In [17]:
train_cols = train.drop('Col2', axis=1).columns.values 
test_cols = test.drop('Col1', axis=1).columns.values

In [18]:
# Check if all columns in train are avialable in test
for x in train_cols:
    if x not in test_cols:
        print(x)

In [19]:
# Check if all columns in test are avialable in train
for x in test_cols:
    if x not in train_cols:
        print(x)

In [20]:
# Check if dtypes of features in train and test datasets are same, if not then look into it.
miss_cols = []

for x in train_cols:
    if train[x].dtype != test[x].dtype:
        print(x)
        miss_cols.append(x)

Col702
Col733
Col742
Col747
Col754
Col763
Col791
Col822
Col831
Col836
Col843
Col852
Col918
Col923


In [21]:
train[miss_cols].dtypes

Col702    float64
Col733    float64
Col742    float64
Col747     object
Col754    float64
Col763    float64
Col791    float64
Col822    float64
Col831    float64
Col836     object
Col843    float64
Col852    float64
Col918      int64
Col923      int64
dtype: object

In [22]:
test[miss_cols].dtypes

Col702     object
Col733     object
Col742     object
Col747    float64
Col754     object
Col763     object
Col791     object
Col822     object
Col831     object
Col836    float64
Col843     object
Col852     object
Col918    float64
Col923    float64
dtype: object

#### `MISMATCH IN DATA TYPES`

#### `Col702`

In [23]:
train.Col702.isnull().sum()/len(train)

0.9819078947368421

In [24]:
test.Col702.isnull().sum()/len(test)

0.9246159866940612

In [25]:
train.Col702.unique()

array([       nan, 0.        , 0.07985957, 0.05714286, 0.25555063,
       0.06998543, 0.0581663 , 0.44261958])

In [26]:
test.Col702.unique()

array([nan, '0.0', '0', '-'], dtype=object)

In [27]:
# Data and data types does not match for the features and also feature contains 98% misising values hence we can drop
train.drop('Col702', axis=1, inplace=True)
test.drop('Col702', axis=1, inplace=True)

#### `Col733`

In [28]:
train.Col733.isnull().sum()/len(train)

0.9669834307992202

In [29]:
test.Col733.isnull().sum()/len(test)

0.9537716466099208

In [30]:
train.Col733.unique()

array([            nan,  2.83473355e-01,  6.48387240e-02,  1.86335340e-01,
        4.47213596e-01,  2.09956264e-01,  1.24179850e-02,  2.23606798e-01,
        6.39602149e-01,  4.69476478e-01, -1.88982237e-01,  1.88982237e-01,
        3.75454332e-01,  9.46696240e-02,  6.00000000e-01,  3.49927106e-01,
        3.52040199e-01, -9.44911180e-02,  7.32498609e-01, -2.23606798e-01,
        1.09408418e-01, -1.20822523e-01, -1.09439083e-01, -3.58790453e-01,
        3.61351114e-01,  4.07877300e-03,  3.87298335e-01, -2.67632600e-02,
       -4.47213595e-01,  0.00000000e+00,  2.09654596e-01,  4.34103499e-01,
        3.86188240e-01,  1.04769305e-01, -2.00000000e-01, -5.55000000e-18,
        6.92820323e-01,  2.19453408e-01,  1.49496418e-01, -6.99854210e-02,
        4.38676931e-01,  3.54787212e-01,  2.58774585e-01, -1.93741205e-01,
       -2.09956264e-01,  1.03870340e-01, -3.49927103e-01, -3.03202472e-01,
        4.11276509e-01,  4.00891863e-01,  2.45142409e-01,  6.99854210e-02,
        4.49866829e-01,  

In [31]:
test.Col733.unique()

array([nan, '0.349927106', '0.23489684', '0.23879256899999998',
       '0.326225572', '-0.20995626399999998', '0.06998542099999999',
       '0.283473355', '0.100574803', '-0.09449111800000001', '0.43723953',
       '0.0', '0.482371579', '-0.223606798', '-0.23093640199999999',
       '-0.287181807', '0.36596252700000004', '0.188982237',
       '-0.0054591330000000006', '0.350883835', '-0.12235312699999999',
       '0.20341128600000002', '-0.124833495', '-1.11e-17', '0.069161739',
       '0.20995626399999998', '0.223606798', '0.49023328899999996',
       '0.36846708799999994', '0.6', '-0.2', '0.11176201300000001',
       '0.461541869', '-5.55e-18', '0.267600457', '0.35689082200000005',
       '-0.6', '-3.97e-18', '-0.12020362400000001', '0.2', '0.447213596',
       '0.338943084', '-0.164954156', '0.399347441', '0.039904182',
       '-0.42405191', '0.356429936', '0.09449111800000001', '0.428811668',
       '-0.06998542099999999', '0.456012469', '-0.063718173',
       '-0.188982237', '-0.1

In [32]:
# Features contains 95% misising values hence we can drop
train.drop('Col733', axis=1, inplace=True)
test.drop('Col733', axis=1, inplace=True)

#### `Col742`

In [33]:
train.Col742.isnull().sum()/len(train)

0.9504751461988304

In [34]:
test.Col742.isnull().sum()/len(test)

0.961843263868506

In [35]:
train.Col742.unique()

array([            nan,  4.63737801e-01,  1.88982237e-01,  6.99854210e-02,
       -2.00000000e-01,  4.47213596e-01,  2.03394410e-02, -9.44911180e-02,
       -6.99854210e-02,  3.49927106e-01,  2.39045722e-01, -6.00000000e-01,
        9.44911180e-02,  6.00000000e-01,  5.95000000e-18, -2.19577516e-01,
       -2.23606798e-01,  0.00000000e+00,  7.31925060e-02, -2.83473355e-01,
        1.15824177e-01,  3.43039010e-01,  2.00000000e-01,  2.83473355e-01,
        2.09956264e-01, -3.49927106e-01,  1.88768400e-03,  4.42626668e-01,
       -1.88982237e-01,  2.23606798e-01,  3.97000000e-18,  2.74694228e-01,
        2.78314400e-03,  1.11000000e-17, -2.09956264e-01, -4.47213595e-01,
        1.98000000e-18, -1.20989807e-01,  2.26960325e-01,  2.14108222e-01,
       -4.31020840e-02, -4.42626668e-01, -4.31532011e-01, -1.48519260e-01,
       -1.02448167e-01, -2.77140550e-02, -3.97000000e-18,  5.41870980e-02,
        1.03436833e-01,  2.24747745e-01,  5.08164140e-02, -8.71795930e-02,
       -5.55000000e-18,  

In [36]:
test.Col742.unique()

array(['0', nan, '-', '1', '3', '7', '0.305620332', '0.349927106',
       '0.447213596', '0.205395959', '-0.2', '0.223606798',
       '-0.20995626399999998', '-0.122938478', '-0.06998542099999999',
       '-0.283473355', '0.20995626399999998', '-0.136930639',
       '-0.188982237', '3.97e-18', '-0.349927106', '-0.447213595', '-0.6',
       '0.06998542099999999', '0.402603716', '0.188982237',
       '-0.076696499', '0.5606419979999999', '-0.223606798',
       '0.09449111800000001', '-0.09449111800000001',
       '-0.21543175899999997', '-0.007523264', '-0.19931998',
       '-0.226960325', '-3.97e-18', '-0.23131100100000002', '0.6',
       '-0.554105809', '0.579500557', '-0.17689318899999998', '0.2',
       '0.16464052099999998', '0.16776615', '0.0', '-1.11e-17',
       '-0.21167196800000002', '-0.037986859', '-0.22131333399999997',
       '0.331970001', '0.283473355', '-0.36596252700000004',
       '0.07319250599999999', '-0.017498297', '-0.397652424',
       '-0.15262449', '-0.12483755

In [37]:
# feature has 98% misising values hence we can drop
train.drop('Col742', axis=1, inplace=True)
test.drop('Col742', axis=1, inplace=True)

#### `Col747`

In [38]:
train.Col747.isnull().sum()/len(train)

0.9618664717348928

In [39]:
test.Col747.isnull().sum()/len(test)

0.9691810977399472

In [40]:
train.Col747.unique()

array([nan, '-', '0', '1', '5', '3'], dtype=object)

In [41]:
test.Col747.unique()

array([            nan,  4.11269288e-01,  2.83473355e-01,  2.09956264e-01,
        2.24376165e-01,  3.55847599e-01,  4.73924065e-01,  9.44911180e-02,
        6.02395850e-01, -6.99854210e-02,  3.49927106e-01,  3.09097116e-01,
       -7.35997940e-02,  4.47213596e-01,  3.76132787e-01,  1.10260451e-01,
        6.00000000e-01,  2.83470539e-01,  5.25629698e-01,  3.32889102e-01,
        5.06985170e-01,  1.22856744e-01, -2.27866677e-01,  4.41033637e-01,
        4.33781801e-01,  3.82595064e-01, -9.44911180e-02, -2.00000000e-01,
       -2.28116544e-01, -7.49520870e-02,  1.88982237e-01,  5.04653546e-01,
        0.00000000e+00, -6.00000000e-01, -1.22547966e-01,  3.64590422e-01,
        4.09068368e-01, -2.23606798e-01,  4.35224125e-01,  4.08771315e-01,
        4.43942055e-01,  5.52385450e-02, -3.49927106e-01,  1.33630621e-01,
        3.07022000e-02,  4.36615390e-01,  2.23606798e-01,  1.27321581e-01,
        4.52536911e-01,  3.32086197e-01,  2.23761948e-01,  5.04156438e-01,
        5.76298336e-01,  

In [42]:
# feature has 96% misising values hence we can drop
train.drop('Col747', axis=1, inplace=True)
test.drop('Col747', axis=1, inplace=True)

#### `Col754`

In [43]:
train.Col754.isnull().sum()/len(train)

0.949317738791423

In [44]:
test.Col754.isnull().sum()/len(test)

0.8788768222287447

In [45]:
train.Col754.unique()

array([            nan,  2.18704536e-01,  3.00922561e-01,  0.00000000e+00,
        2.16011264e-01,  4.47213596e-01,  2.09956265e-01,  8.32693000e-04,
        9.99999790e-02, -1.67693020e-02,  3.10859468e-01, -1.88979757e-01,
        7.98595710e-02,  3.72194919e-01,  7.16342400e-02,  1.91662970e-01,
        5.77350270e-02,  5.99999338e-01,  3.49927116e-01,  2.46823932e-01,
       -1.31236997e-01,  2.09955788e-01,  3.35218519e-01, -2.23606818e-01,
       -8.26169070e-02, -1.35937761e-01, -1.04469348e-01, -3.71489565e-01,
       -1.41421356e-01, -9.44919080e-02,  3.49927102e-01,  3.45638999e-01,
       -5.21094270e-02,  1.63640522e-01,  1.92190802e-01, -4.47213374e-01,
        2.35973160e-01,  4.08099329e-01,  3.01441024e-01,  1.41421356e-01,
        2.99999788e-01, -2.00000000e-01,  3.00000059e-01,  2.55550626e-01,
        2.23607073e-01,  3.99984223e-01,  2.18703337e-01,  2.18704516e-01,
       -1.75963440e-02,  2.70075923e-01,  6.53837290e-02, -4.47214895e-01,
       -6.99854240e-02,  

In [46]:
test.Col754.unique()

array([nan, '0.255550626', '0.0', '0.12995089', '0.109986363',
       '0.185576872', '-0.209898855', '0.06998542099999999',
       '0.159719141', '-0.001457966', '-0.13122268', '0.040406103',
       '-7.93e-18', '0.49481681', '-0.22360674100000003', '-0.229849969',
       '0.233550383', '0.246248152', '0.131222665', '-0.223606798',
       '-0.37529049600000003', '-0.136507119', '-0.052743795',
       '-0.217642129', '-1.11e-17', '0.165375297', '0.20995626399999998',
       '0.223606814', '-0.094491361', '-0.029918942999999996',
       '0.380055619', '0.223606798', '0.141421356',
       '-0.19999998300000002', '0.143624108', '0.289577449',
       '0.057140606', '-0.099999999', '0.194040438', '0.057735027',
       '0.193081132', '-0.6', '3.97e-18', '-0.153186077', '-2.73e-08',
       '0.447213608', '-0.101577553', '0.131223026',
       '0.13122267199999998', '0.050194170999999996', '0.14580145',
       '-0.199999922', '0.223606744', '-0.223606799', '0.3',
       '0.138646785', '0.1811406

In [47]:
# Feature has 90% misising values hence we can drop
train.drop('Col754', axis=1, inplace=True)
test.drop('Col754', axis=1, inplace=True)

#### `Col763`

In [48]:
train.Col763.isnull().sum()/len(train)

0.9328094541910331

In [49]:
test.Col763.isnull().sum()/len(test)

0.8868995205948538

In [50]:
train.Col763.unique()

array([            nan,  1.90702868e-01,  1.31222665e-01,  0.00000000e+00,
        6.99854210e-02, -2.00000000e-01,  1.73205083e-01,  1.93005180e-02,
       -1.59719142e-01, -1.27775313e-01, -6.34000000e-18,  3.42857143e-01,
       -1.27775314e-01, -6.99854210e-02, -5.54609580e-02, -5.99999635e-01,
        1.59719140e-02,  6.00000005e-01,  2.91605940e-02, -2.74393423e-01,
       -2.23606798e-01,  1.33542160e-02, -2.83473355e-01, -2.23606763e-01,
        3.96315370e-02,  1.39238462e-01,  2.00000000e-01,  2.83473355e-01,
       -7.07106780e-02,  1.27775313e-01,  2.09956264e-01, -3.49927106e-01,
       -2.23606799e-01, -8.94985100e-03,  3.22996106e-01, -1.59719141e-01,
       -9.44911200e-02,  4.47213596e-01,  1.45802960e-01,  1.59719141e-01,
        1.00000000e-01, -2.33284734e-01, -4.37409000e-02, -1.88982237e-01,
       -1.88982240e-01,  3.97000000e-18, -2.28571429e-01, -9.44911180e-02,
       -2.90289320e-02, -3.02131038e-01, -1.00000000e-01, -9.44911120e-02,
        4.47213595e-01, -

In [51]:
test.Col763.unique()

array(['0', nan, '-', '1', '0.326166446', '0.255548809', '0.447213596',
       '0.214222192', '-0.19999999300000001', '0.1', '0.0',
       '0.22360653100000003', '-0.255550632', '-0.228996851',
       '-0.06998542099999999', '-0.291605922', '-0.131965775',
       '-0.283473354', '0.127775313', '-0.016694786', '-0.188982225',
       '-0.107142857', '0.349927107', '0.349927106', '-0.349927106',
       '0.223606798', '-0.447213594', '-0.6', '-0.447213596',
       '0.06998542099999999', '-0.18898223600000003', '-0.283473355',
       '0.44623561700000003', '-0.188982237', '-0.342857143',
       '0.188982237', '-0.143747227', '0.069985422', '0.332215814',
       '-0.28571428600000004', '-0.20026159100000002',
       '-0.25555057600000003', '-0.447213595', '-0.349927111',
       '-0.255550626', '0.343375854', '0.223606794', '-0.131965777',
       '-0.300000002', '-0.3', '-0.20995626399999998',
       '0.16071428699999998', '0.209956261', '0.20995626399999998',
       '-0.09449111800000001', '

In [52]:
# feature has 90% misising values hence we can drop
train.drop('Col763', axis=1, inplace=True)
test.drop('Col763', axis=1, inplace=True)

#### `Col791`

In [53]:
train.Col791.isnull().sum()/len(train)

0.9817860623781677

In [54]:
test.Col791.isnull().sum()/len(test)

0.9245670678015849

In [55]:
train.Col791.unique()

array([        nan,  0.        ,  0.12777531,  0.05714286,  0.25555063,
        0.06998543, -0.02009183,  0.44261958])

In [56]:
test.Col791.unique()

array([nan, '0', '-', '0.0'], dtype=object)

In [57]:
# Feature contains 98% misising values hence we can drop
train.drop('Col791', axis=1, inplace=True)
test.drop('Col791', axis=1, inplace=True)

#### `Col822`

In [58]:
train.Col822.isnull().sum()/len(train)

0.9673489278752436

In [59]:
test.Col822.isnull().sum()/len(test)

0.9537716466099208

In [60]:
train.Col822.unique()

array([            nan,  3.49927106e-01,  6.48387240e-02,  9.45680710e-02,
        4.47213596e-01,  2.09956264e-01,  1.24179850e-02,  2.23606798e-01,
        6.39602149e-01,  4.69476478e-01, -3.49927106e-01,  3.75454332e-01,
        5.16886270e-02,  6.00000000e-01,  4.31192217e-01, -2.09956264e-01,
        7.32498609e-01, -2.23606798e-01, -2.66385490e-02, -3.44625120e-01,
       -3.40635273e-01, -3.58790453e-01,  4.13030095e-01,  4.07877300e-03,
        3.87298335e-01, -2.67632600e-02, -4.47213595e-01, -6.99854210e-02,
        2.07127833e-01,  4.34103499e-01,  3.86188240e-01,  1.04769305e-01,
       -2.00000000e-01,  0.00000000e+00,  6.92820323e-01,  2.19453408e-01,
        1.49496418e-01,  4.38676931e-01,  4.01005371e-01,  1.80701581e-01,
       -1.93741205e-01, -5.14243970e-02, -3.49927103e-01, -4.47367281e-01,
        4.78221541e-01,  2.45142409e-01,  6.99854210e-02,  4.49866829e-01,
        3.58292494e-01, -2.09956262e-01, -6.64589220e-02,  1.82574186e-01,
        4.42435874e-01, -

In [61]:
test.Col822.unique()

array([nan, '0.349927106', '0.23489684', '0.23956286699999998',
       '0.400694318', '-0.20995626399999998', '0.06998542099999999',
       '-0.10238248400000001', '0.43723953', '-0.06998542099999999',
       '0.482371579', '-0.223606798', '-0.23093640199999999',
       '-0.287181807', '0.44262666799999995', '0.20995626399999998',
       '-0.0054591330000000006', '0.350883835', '-0.12235312699999999',
       '0.16265401', '-0.124833495', '0.0', '0.069161739', '0.223606798',
       '0.49023328899999996', '0.36846708799999994', '0.6', '-0.2',
       '0.08325307400000001', '0.461541869', '0.267600457',
       '0.35689082200000005', '-0.6', '-0.12020362400000001', '0.2',
       '0.447213596', '0.11386477099999999', '0.338943084',
       '-0.164954156', '0.399347441', '-0.118367822', '-0.42405191',
       '0.410778246', '0.481194381', '0.456012469', '-0.063718173',
       '-0.349927106', '-0.12979131900000002', '-0.147929864',
       '0.13703048', '-0.21659878800000001', '0.3851774129999999

In [62]:
# feature has 96% misising values hence we can drop
train.drop('Col822', axis=1, inplace=True)
test.drop('Col822', axis=1, inplace=True)

#### `Col831`

In [63]:
train.Col831.isnull().sum()/len(train)

0.9526681286549707

In [64]:
test.Col831.isnull().sum()/len(test)

0.9641913707073672

In [65]:
train.Col831.unique()

array([            nan,  4.63737801e-01,  2.09956264e-01,  6.99854210e-02,
       -2.00000000e-01,  4.47213596e-01, -7.83251000e-02, -2.09956264e-01,
       -6.99854210e-02,  3.49927106e-01,  2.39045722e-01, -6.00000000e-01,
        6.00000000e-01, -4.42626668e-01, -2.23606798e-01,  0.00000000e+00,
        9.52000000e-18,  6.44875540e-02,  3.43039010e-01,  2.00000000e-01,
       -3.49927106e-01, -9.19234990e-02,  4.42626668e-01,  2.23606798e-01,
        2.74694228e-01,  2.78314400e-03, -4.47213595e-01, -1.20989807e-01,
        2.13332991e-01, -4.31020840e-02, -4.31532011e-01, -3.13243304e-01,
       -1.02448167e-01, -2.77140550e-02, -1.74359190e-02,  1.03436833e-01,
        2.24747745e-01, -2.34921840e-02, -8.71795930e-02,  2.21586457e-01,
        2.21353688e-01,  1.11000000e-17,  1.68164240e-02, -8.68744490e-02,
        8.31485500e-02, -4.52969123e-01,  1.26599166e-01,  1.56167486e-01,
       -1.49421081e-01, -2.61268030e-02,  1.96173304e-01,  2.27880391e-01,
        5.02668510e-02, -

In [66]:
test.Col831.unique()

array(['0', nan, '-', '1', '0.305620332', '0.349927106', '0.447213596',
       '0.205395959', '-0.2', '0.223606798', '-0.20995626399999998',
       '-0.122938478', '-0.06998542099999999', '0.20995626399999998',
       '-0.136930639', '-0.349927106', '-0.447213595', '-0.6',
       '0.06998542099999999', '0.402603716', '-0.076696499',
       '0.5606419979999999', '-0.223606798', '-0.21543175899999997',
       '-0.19931998', '-0.094368323', '-0.500396954', '0.6',
       '-0.554105809', '0.579500557', '-0.17689318899999998', '0.2',
       '0.14312243', '0.16776615', '0.0', '-5.55e-18',
       '-0.21167196800000002', '-0.149224801', '-0.22131333399999997',
       '0.331970001', '-9.52e-18', '-0.017498297', '-0.397652424',
       '-0.15262449', '-0.12483755699999999', '-0.37564327700000005',
       '-6.34e-18', '-0.20899904', '0.01327184', '0.347415301',
       '-0.18257418600000003', '0.02998002', '-0.450341001',
       '0.018196863', '-0.194166363', '0.346498814',
       '-0.44262666799999

In [67]:
# feature has 95% misising values hence we can drop
train.drop('Col831', axis=1, inplace=True)
test.drop('Col831', axis=1, inplace=True)

#### `Col836`

In [68]:
train.Col836.isnull().sum()/len(train)

0.9619883040935673

In [69]:
test.Col836.isnull().sum()/len(test)

0.9695235299872811

In [70]:
train.Col836.unique()

array([nan, '-', '0', '5'], dtype=object)

In [71]:
test.Col836.unique()

array([            nan,  4.88458596e-01,  3.49927106e-01,  2.09956264e-01,
        2.24376165e-01,  3.21187184e-01,  4.73924065e-01,  6.99854210e-02,
        6.02395850e-01, -6.99854210e-02,  3.09097116e-01, -7.35997940e-02,
        4.47213596e-01,  4.47943190e-01,  1.10260451e-01,  6.00000000e-01,
        3.49917407e-01,  5.25629698e-01,  3.32889102e-01,  5.06985170e-01,
        1.22856744e-01, -2.27866677e-01,  4.41033637e-01,  4.33781801e-01,
        4.43722648e-01, -2.09956264e-01, -2.00000000e-01, -3.87722849e-01,
       -3.40664070e-01,  5.04653546e-01,  0.00000000e+00, -6.00000000e-01,
       -1.22547966e-01,  3.64590422e-01,  4.83122536e-01, -2.23606798e-01,
        4.35224125e-01,  4.08771315e-01,  4.43942055e-01,  5.52385450e-02,
       -3.49927106e-01, -1.27000000e-17,  3.07022000e-02,  4.36615390e-01,
        2.23606798e-01,  1.27321581e-01,  4.52536911e-01,  3.46674225e-01,
       -5.53283340e-02,  5.04156438e-01,  5.76298336e-01,  2.96334000e-02,
        6.05752768e-01, -

In [72]:
# feature has 98% misising values hence we can drop
train.drop('Col836', axis=1, inplace=True)
test.drop('Col836', axis=1, inplace=True)

#### `Col843`

In [73]:
train.Col843.isnull().sum()/len(train)

0.9495614035087719

In [74]:
test.Col843.isnull().sum()/len(test)

0.8788279033362685

In [75]:
train.Col843.unique()

array([            nan,  3.49927108e-01,  3.00922561e-01,  0.00000000e+00,
        3.45618023e-01,  4.47213596e-01,  2.09956265e-01,  8.32693000e-04,
        9.99999790e-02, -1.67693020e-02,  3.10859468e-01, -3.49929920e-01,
        1.27775313e-01,  3.72194919e-01, -9.38253710e-02,  3.06660751e-01,
        5.77350270e-02,  5.99999338e-01,  3.49927116e-01,  3.94918292e-01,
       -2.09979195e-01,  2.09955788e-01,  3.35218519e-01, -2.23606818e-01,
       -1.32187036e-01, -3.66650390e-01, -3.35073236e-01, -3.71489565e-01,
       -1.41421356e-01, -2.09956409e-01,  3.49927102e-01,  3.70055791e-01,
       -5.21094270e-02,  1.63640522e-01,  1.92190802e-01, -4.47213374e-01,
       -6.99854210e-02,  2.74508794e-01,  4.08099329e-01,  3.01441024e-01,
        1.41421356e-01,  2.99999788e-01, -2.00000000e-01,  3.00000059e-01,
        2.55550626e-01,  2.23607073e-01,  3.99984223e-01,  3.49924881e-01,
        3.49927128e-01, -1.75963440e-02,  2.70075923e-01,  6.53837290e-02,
       -4.47214895e-01, -

In [76]:
test.Col843.unique()

array([nan, '0.255550626', '0.0', '0.12995089', '0.175978183',
       '0.296922995', '-0.209898855', '0.06998542099999999',
       '-0.447010279', '-0.209956267', '0.040406103', '-0.06998542',
       '0.49481681', '-0.22360674100000003', '-0.229849969',
       '0.233550383', '0.393997043', '0.20995626399999998',
       '-0.223606798', '-0.37529049600000003', '-0.136507119',
       '-0.247431373', '-0.217642129', '0.165375297', '0.223606814',
       '-0.209956035', '-0.029918942999999996', '0.380055619',
       '0.223606798', '0.141421356', '-0.19999998300000002',
       '0.106219251', '0.289577449', '0.057140606', '-0.099999999',
       '0.194040438', '0.057735027', '0.193081132', '-0.6',
       '-0.06998541900000001', '-0.153186077', '-2.73e-08', '0.447213608',
       '-0.256986263', '0.20995645899999998', '0.050194170999999996',
       '0.127775215', '-0.199999922', '0.223606744', '-0.223606799',
       '0.3', '0.138646785', '0.18114065199999999', '0.18342509899999998',
       '-0.69

In [77]:
# feature contains 95% misising values hence we can drop
train.drop('Col843', axis=1, inplace=True)
test.drop('Col843', axis=1, inplace=True)

#### `Col852`

In [78]:
train.Col852.isnull().sum()/len(train)

0.9348806042884991

In [79]:
test.Col852.isnull().sum()/len(test)

0.8891987085412386

In [80]:
train.Col852.unique()

array([            nan,  1.90702868e-01,  2.09956264e-01,  0.00000000e+00,
        6.99854210e-02, -2.00000000e-01,  1.73205083e-01, -8.00526400e-02,
       -2.55550626e-01, -1.27775313e-01,  6.34000000e-18,  3.42857143e-01,
       -1.27775314e-01, -6.99854210e-02, -5.54609580e-02, -5.99999635e-01,
        2.55550630e-02,  6.00000005e-01, -2.55550630e-02, -4.39029474e-01,
       -2.23606798e-01, -8.49572000e-02, -2.23606763e-01, -2.61595810e-02,
        1.39238462e-01,  2.00000000e-01,  3.49927106e-01, -7.07106780e-02,
        1.27775313e-01, -3.49927106e-01, -2.23606799e-01, -1.05888988e-01,
        3.22996106e-01, -2.09956261e-01,  4.47213596e-01,  2.55550626e-01,
        1.00000000e-01, -6.99854200e-02, -3.49927112e-01, -2.28571429e-01,
       -2.09956264e-01, -2.90289320e-02, -3.02131038e-01, -1.00000000e-01,
       -2.09956258e-01,  4.47213595e-01, -3.49927083e-01, -3.00000000e-01,
       -4.47213595e-01, -2.09956263e-01, -3.06660751e-01, -3.14285714e-01,
       -1.71428571e-01, -

In [81]:
test.Col852.unique()

array(['0', nan, '-', '6', '0.0', '0.326166446', '0.255548809',
       '0.447213596', '0.214222192', '-0.19999999300000001', '0.1',
       '0.22360653100000003', '-0.255550632', '-0.228996851',
       '-0.06998542099999999', '-0.131965775', '0.127775313',
       '-0.016694786', '-0.34992697700000003', '-0.171428571',
       '0.349927107', '0.349927106', '-0.349927106', '0.223606798',
       '-0.447213594', '-0.6', '-0.447213596', '0.06998542099999999',
       '0.44623561700000003', '-0.342857143', '0.20995626399999998',
       '-0.285714287', '0.069985422', '0.332215814',
       '-0.28571428600000004', '-0.20026159100000002',
       '-0.25555057600000003', '-0.447213595', '-0.349927111',
       '-0.255550626', '0.343375854', '0.223606794', '-0.131965777',
       '-0.300000002', '-0.3', '-0.20995626399999998', '-0.349927105',
       '0.164957228', '0.209956261', '-0.10222025', '-0.199999992',
       '-0.127775313', '0.099999845', '-0.159008126', '-0.223606798',
       '-0.24064560899999

In [82]:
# feature contains 93% misising values hence we can drop
train.drop('Col852', axis=1, inplace=True)
test.drop('Col852', axis=1, inplace=True)

#### `Col918`

In [83]:
train.Col918.isnull().sum()/len(train)

0.0

In [84]:
test.Col918.isnull().sum()/len(test)

0.0

In [85]:
train.Col918.unique()

array([   16000,   630316,        0, 14905945,    10000,     1125,
           2000,   712207,    17250,    11540,    33700,    20000,
          35000,     5750,    10850,    80000,    15000,   192174,
          22276,     1000,    22840,    11000,     7250,    12450,
          30000,    70000,   153663,   200000,    73000,    11701,
           5500,    21000,    32000,     7700,     9960,     6850,
          28000,     4195,      690,    29250,     1650,    10700,
          67000,    48700,    12000,     8373,   100257,    21179,
          15800,   141550,    10190,    21900,    52117,    71600,
           2500,     3000,    25500,   272501,    33000,     5450,
           3080,     7000,     6000,    25000,   165000,     3004,
           5000,    20250,    18000,   152541,    50000,    19257,
           4957,     9800,   120905,    24600,   257850,   160000,
           3748,   120000,    37640,    45700,     1500,    26050,
          11323,    72663,    40150,     2250,     7800,     3

In [86]:
test.Col918.unique()

array([0.0000000e+00, 1.5687720e+06, 2.3437420e+06, 2.3150000e+03,
       2.7270000e+04, 2.0000000e+03, 4.0000000e+04, 1.9931000e+04,
       3.6000000e+03, 8.2000000e+04, 2.6150000e+04, 1.0222000e+05,
       2.4000000e+04, 6.4400000e+03, 1.7000000e+04, 1.0000000e+05,
       5.8150000e+03, 2.0393000e+05, 6.6666000e+04, 1.1000000e+04,
       2.0000000e+05, 5.5053000e+04, 7.5000000e+03, 1.3580000e+04,
       1.2000000e+04, 4.5000000e+05, 1.5000000e+05, 4.5910000e+04,
       3.0000000e+04, 9.0000000e+03, 1.0000000e+03, 1.2500000e+04,
       2.1259000e+04, 1.1500000e+03, 1.2414000e+04, 1.4100000e+06,
       1.5000000e+04, 2.5000000e+04, 1.0000000e+04, 1.1600000e+05,
       2.4100000e+04, 5.0000000e+04, 3.2000000e+03, 4.7500000e+04,
       1.9477000e+06, 3.0000000e+05, 6.0000000e+04, 1.1500000e+04,
       2.5000000e+05, 5.0000000e+05, 5.0435000e+04, 1.4396000e+04,
       4.3950000e+03, 5.0000000e+03, 2.3550000e+04, 4.9000000e+04,
       1.2005000e+04, 4.7300000e+04, 1.4097000e+04, 1.0435000e

In [87]:
# Changing the type as that in train
test['Col918'] = test.Col918.astype('int64')

#### `Col923`

In [88]:
train.Col923.isnull().sum()/len(train)

0.0

In [89]:
test.Col923.isnull().sum()/len(test)

0.0

In [90]:
train.Col923.unique()

array([   16000,   630316,        0, 14905945,    10000,     1125,
           2000,   712207,    17250,    11540,    33700,    20000,
          35000,     5750,    10850,    80000,    15000,   192174,
          22276,     1000,    22840,    11000,     7250,    12450,
          30000,    70000,   153663,   200000,    73000,    11701,
           5500,    21000,    32000,     7700,     9960,     6850,
          28000,     4195,      690,    29250,     1650,    10700,
          67000,    48700,    12000,     8373,   100257,    21179,
          15800,   141550,    10190,    21900,    52117,    71600,
           2500,     3000,    25500,   272501,    33000,     5450,
           3080,     7000,     6000,    25000,   165000,     3004,
           5000,    20250,    18000,   152541,    50000,    19257,
           4957,     9800,   120905,    24600,   257850,   160000,
           3748,   120000,    37640,    45700,     1500,    26050,
          11323,    72663,    40150,     2250,     7800,     3

In [91]:
test.Col923.unique()

array([0.0000000e+00, 1.5687720e+06, 2.3437420e+06, 2.3150000e+03,
       2.7270000e+04, 2.0000000e+03, 4.0000000e+04, 1.9931000e+04,
       3.6000000e+03, 8.2000000e+04, 2.6150000e+04, 1.0222000e+05,
       2.4000000e+04, 6.4400000e+03, 1.7000000e+04, 1.0000000e+05,
       5.8150000e+03, 2.0393000e+05, 6.6666000e+04, 1.1000000e+04,
       2.0000000e+05, 5.5053000e+04, 7.5000000e+03, 1.3580000e+04,
       1.2000000e+04, 4.5000000e+05, 1.5000000e+05, 2.0000000e+04,
       3.0000000e+04, 9.0000000e+03, 1.0000000e+03, 1.2500000e+04,
       2.1259000e+04, 1.1500000e+03, 1.2414000e+04, 1.0000000e+04,
       1.5000000e+04, 2.5000000e+04, 1.1600000e+05, 2.4100000e+04,
       5.0000000e+04, 3.2000000e+03, 4.7500000e+04, 1.9477000e+06,
       3.0000000e+05, 1.1500000e+04, 2.5000000e+05, 5.0000000e+05,
       5.0435000e+04, 1.4396000e+04, 4.3950000e+03, 5.0000000e+03,
       2.3550000e+04, 4.9000000e+04, 1.2005000e+04, 4.7300000e+04,
       1.4097000e+04, 1.0435000e+04, 1.6700000e+05, 2.5470000e

In [92]:
# Changing the type as that in train
test['Col923'] = test.Col923.astype('int64')

#### `FINAL CHECK FOR DATA TYPE MISMATCH`

In [93]:
# Check if dtypes of columns are same
miss_cols = []

for x in train.drop('Col2', axis=1).columns.values:
    if train[x].dtype != test[x].dtype:
        print(x)
        miss_cols.append(x)

#### `SAVING DATA TYPES`

In [94]:
# col_float = train.select_dtypes('float64').columns.values
# col_int = train.select_dtypes('int64').columns.values

### `CHECK MISSING %`

In [95]:
null_features = train.isnull().sum()/len(train)

null_features = null_features[null_features > 0]

count_null = len(null_features.index.values)

print(f'There are {count_null} features with missing values.... \n')

# print(null_features.index.values)

There are 719 features with missing values.... 



In [96]:
# Checking features with more than 20% mising values
null_cols = null_features[null_features >= 0.2].index.values

print(f'There are {len(null_cols)} Features with more than 20% missing values.....\n')

print(null_cols)

There are 265 Features with more than 20% missing values.....

['Col19' 'Col20' 'Col28' 'Col37' 'Col38' 'Col39' 'Col40' 'Col41' 'Col95'
 'Col97' 'Col98' 'Col99' 'Col100' 'Col101' 'Col102' 'Col103' 'Col104'
 'Col105' 'Col109' 'Col110' 'Col111' 'Col112' 'Col113' 'Col114' 'Col115'
 'Col116' 'Col117' 'Col118' 'Col119' 'Col138' 'Col139' 'Col140' 'Col141'
 'Col142' 'Col143' 'Col144' 'Col145' 'Col146' 'Col147' 'Col148' 'Col149'
 'Col150' 'Col151' 'Col152' 'Col153' 'Col154' 'Col155' 'Col156' 'Col157'
 'Col158' 'Col159' 'Col171' 'Col185' 'Col249' 'Col251' 'Col252' 'Col253'
 'Col254' 'Col259' 'Col261' 'Col262' 'Col263' 'Col265' 'Col266' 'Col271'
 'Col273' 'Col274' 'Col275' 'Col276' 'Col281' 'Col283' 'Col284' 'Col285'
 'Col287' 'Col288' 'Col334' 'Col335' 'Col336' 'Col338' 'Col339' 'Col340'
 'Col341' 'Col342' 'Col343' 'Col344' 'Col347' 'Col348' 'Col351' 'Col352'
 'Col353' 'Col355' 'Col356' 'Col357' 'Col359' 'Col360' 'Col361' 'Col362'
 'Col363' 'Col364' 'Col365' 'Col368' 'Col369' 'Col372' 'Col373' 

In [97]:
# Features with unique values less than 10 and same unique values in test and train
u_10 = []

for x in null_cols:
    mina = train[x].min()
    maxa = train[x].max()
    count = len(train[x].unique())
    print(f'Feature: {x} | Min Value: {mina} | Max Value: {maxa} | Unique Count: {count}')
    
    if count < 10:
        u_10.append(x)

Feature: Col19 | Min Value: -992.569191 | Max Value: 16104.247659999999 | Unique Count: 2763
Feature: Col20 | Min Value: -340.921462 | Max Value: 3782.2160259999996 | Unique Count: 3203
Feature: Col28 | Min Value: -1.414213565 | Max Value: 1.414213564 | Unique Count: 3885
Feature: Col37 | Min Value: 0.0 | Max Value: 152.0 | Unique Count: 65
Feature: Col38 | Min Value: 0.0 | Max Value: 150.0 | Unique Count: 17
Feature: Col39 | Min Value: 0.0 | Max Value: 7.0 | Unique Count: 9
Feature: Col40 | Min Value: 0.0 | Max Value: 166.0 | Unique Count: 72
Feature: Col41 | Min Value: 0.0 | Max Value: 218.0 | Unique Count: 29
Feature: Col95 | Min Value: 0.0 | Max Value: 10.0 | Unique Count: 12
Feature: Col97 | Min Value: 0.0 | Max Value: 10.0 | Unique Count: 12
Feature: Col98 | Min Value: 0.0 | Max Value: 10.0 | Unique Count: 11
Feature: Col99 | Min Value: 0.0 | Max Value: 10.0 | Unique Count: 12
Feature: Col100 | Min Value: 0.0 | Max Value: 7.0 | Unique Count: 9
Feature: Col101 | Min Value: 0.0 | M

Feature: Col569 | Min Value: 0.0 | Max Value: 3.745318352 | Unique Count: 4319
Feature: Col570 | Min Value: 0.0 | Max Value: 2.0 | Unique Count: 4
Feature: Col571 | Min Value: 0.0 | Max Value: 3.745318352 | Unique Count: 3274
Feature: Col572 | Min Value: 0.0 | Max Value: 2.449490375 | Unique Count: 716
Feature: Col573 | Min Value: 0.0 | Max Value: 2.449490559 | Unique Count: 10500
Feature: Col574 | Min Value: 0.0 | Max Value: 2.449492444 | Unique Count: 10841
Feature: Col677 | Min Value: 0.0 | Max Value: 1.0 | Unique Count: 1052
Feature: Col678 | Min Value: 0.0 | Max Value: 5000000.0 | Unique Count: 11497
Feature: Col679 | Min Value: 0.0 | Max Value: 2400000.0 | Unique Count: 11819
Feature: Col685 | Min Value: -0.762220463 | Max Value: 0.768000283 | Unique Count: 3085
Feature: Col687 | Min Value: -0.773458764 | Max Value: 0.7726637059999999 | Unique Count: 8971
Feature: Col688 | Min Value: -0.764565238 | Max Value: 0.7723480770000001 | Unique Count: 2469
Feature: Col689 | Min Value: -0

In [98]:
cols_to_drop = []

for x in null_cols:
    if x not in u_10:
        cols_to_drop.append(x)

In [99]:
# Drop features with more null values
train.drop(columns = cols_to_drop, inplace=True)
test.drop(columns = cols_to_drop, inplace=True)

#### `ROWS WITH 70% MISSING VALUES`

In [100]:
threshold = 0.7

#Dropping rows with missing value rate higher than threshold
train = train.loc[train.isnull().mean(axis=1) < threshold]

### `CHECKING % UNIQUE VALUES FOR FEATURES`

In [101]:
feature = []
value = []

for x in train.drop('Col2', axis=1).columns.values:
    a = len(train[x].unique())
    feature.append(x)
    value.append(a)

In [102]:
train_unique = pd.DataFrame(data = {'feature': feature, 'value': value})

In [103]:
# Features with 4 or less unique valuesd
f_4 = train_unique[train_unique.value < 4].feature.values

print(f'{len(f_4)} Features have less than 4 unique values. \n{f_4}')

32 Features have less than 4 unique values. 
['Col36' 'Col60' 'Col61' 'Col62' 'Col63' 'Col64' 'Col65' 'Col66' 'Col67'
 'Col84' 'Col85' 'Col86' 'Col87' 'Col88' 'Col89' 'Col90' 'Col91' 'Col266'
 'Col288' 'Col724' 'Col974' 'Col975' 'Col1018' 'Col1019' 'Col1067'
 'Col1225' 'Col1269' 'Col1289' 'Col1294' 'Col1955' 'Col1999' 'Col2019']


In [104]:
for x in f_4:
    print(f'Feature: {x} | Unique Values: {train[x].unique()}')

Feature: Col36 | Unique Values: [6 5 4]
Feature: Col60 | Unique Values: [1 2 0]
Feature: Col61 | Unique Values: [1 0 2]
Feature: Col62 | Unique Values: [1 2 0]
Feature: Col63 | Unique Values: [1 0 2]
Feature: Col64 | Unique Values: [1 2 0]
Feature: Col65 | Unique Values: [1 0 2]
Feature: Col66 | Unique Values: [1 0 2]
Feature: Col67 | Unique Values: [1 0 2]
Feature: Col84 | Unique Values: [1 0 2]
Feature: Col85 | Unique Values: [0 1 2]
Feature: Col86 | Unique Values: [1 0 2]
Feature: Col87 | Unique Values: [0 1 2]
Feature: Col88 | Unique Values: [1 0 2]
Feature: Col89 | Unique Values: [0 1 2]
Feature: Col90 | Unique Values: [1 0 2]
Feature: Col91 | Unique Values: [0 1 2]
Feature: Col266 | Unique Values: [nan  2.  1.]
Feature: Col288 | Unique Values: [nan  2.  1.]
Feature: Col724 | Unique Values: [nan  0.]
Feature: Col974 | Unique Values: [0 1]
Feature: Col975 | Unique Values: [0 1 2]
Feature: Col1018 | Unique Values: [0 1 2]
Feature: Col1019 | Unique Values: [0 1]
Feature: Col1067 | Un

### `FEATURES WHERE MIN = MAX`

In [105]:
minmax = []

for x in train.drop('Col2', axis=1).columns.values:
    a = train[x].min()
    b = train[x].max()
    
    if a == b:
        print(f'Feature: {x} | Min: {a} | Max: {b}')
        minmax.append(x)

Feature: Col724 | Min: 0.0 | Max: 0.0


In [106]:
# Drop features with more unique values
if len(minmax) > 0:
    train.drop(columns=minmax, axis=1, inplace=True)
    test.drop(columns=minmax, axis=1, inplace=True)

### `CHECK FOR FEATURES WITH SIMILAR INFORMATION`

In [107]:
# cols = train.drop('Col2', axis=1).columns.values

# for x in cols:
#     if x in train.drop('Col2', axis=1).columns.values:
#         new_cols = train.drop(['Col2', x], axis=1).columns.values
#         for y in new_cols:
#             a = train[x].values
#             b = train[y].values

#             i = 0
#             j = 0

#             while i < len(b):
#                 if a[i] == b[i]:
#                     j = j+1
#                 i = i+1

#             z = round(j/train[x].count()* 100,2)

#             if z > 80:
#                 print(f'Feature {x} & {y} have {z}% common values')
#                 train.drop(y, axis=1, inplace=True)
#                 print(f'Feature {y} dropped...')

In [108]:
# cols = train.drop('Col2', axis=1).columns.values

# df = test[cols]
# df['Col1'] = test.Col1
# test = df

### `SAVING FILE TO DISK`

In [109]:
import os

path = 'G:\\ML - Datahack\\HDFC Bank\\Files'

os.chdir(path)

%pwd

'G:\\ML - Datahack\\HDFC Bank\\Files'

In [110]:
train.to_csv('train.csv', index=False)
test.to_csv('test.csv', index=False)